export const tickerToName: { [key: string]: string } = {
    "NVDA": "NVIDIA Corporation",
    "MSFT": "Microsoft Corporation",
    "AAPL": "Apple Inc.",
    "AMZN": "Amazon.com, Inc.",
    "META": "Meta Platforms, Inc.",
    "AVGO": "Broadcom Inc.",
    "GOOGL": "Alphabet Inc. (Class A)",
    "GOOG": "Alphabet Inc. (Class C)",
    "BRK-B": "Berkshire Hathaway Inc.",
    "TSLA": "Tesla, Inc.",
    "JPM": "JPMorgan Chase & Co.",
    "WMT": "Walmart Inc.",
    "LLY": "Eli Lilly and Company",
    "V": "Visa Inc.",
    "ORCL": "Oracle Corporation",
    "MA": "Mastercard Incorporated",
    "NFLX": "Netflix, Inc.",
    "XOM": "Exxon Mobil Corporation",
    "COST": "Costco Wholesale Corporation",
    "JNJ": "Johnson & Johnson",
    "PLTR": "Palantir Technologies Inc.",
    "HD": "The Home Depot, Inc.",
    "PG": "The Procter & Gamble Company",
    "BAC": "Bank of America Corporation",
    "ABBV": "AbbVie Inc.",
    "CVX": "Chevron Corporation",
    "KO": "The Coca-Cola Company",
    "GE": "General Electric Company",
    "TMUS": "T-Mobile US, Inc.",
    "CSCO": "Cisco Systems, Inc.",
    "WFC": "Wells Fargo & Company",
    "AMD": "Advanced Micro Devices, Inc.",
    "CRM": "Salesforce, Inc.",
    "UNH": "UnitedHealth Group Incorporated",
    "PM": "Philip Morris International Inc.",
    "IBM": "International Business Machines Corporation",
    "MS": "Morgan Stanley",
    "GS": "The Goldman Sachs Group, Inc.",
    "LIN": "Linde plc",
    "ABT": "Abbott Laboratories",
    "INTU": "Intuit Inc.",
    "DIS": "The Walt Disney Company",
    "AXP": "American Express Company",
    "MCD": "McDonald's Corporation",
    "MRK": "Merck & Co., Inc.",
    "RTX": "RTX Corporation",
    "CAT": "Caterpillar Inc.",
    "NOW": "ServiceNow, Inc.",
    "T": "AT&T Inc.",
    "PEP": "PepsiCo, Inc.",
    "ADBE": "Adobe Inc.",
    "QCOM": "QUALCOMM, Incorporated",
    "SBUX": "Starbucks Corporation",
    "PYPL": "PayPal Holdings, Inc.",
    "INTC": "Intel Corporation",
    "BA": "The Boeing Company",
    "C": "Citigroup Inc.",
    "GSK": "GSK plc",
    "NKE": "NIKE, Inc.",
    "TM": "Toyota Motor Corporation",
    "UPS": "United Parcel Service, Inc.",
    "LOW": "Lowe's Companies, Inc.",
    "F": "Ford Motor Company",
    "GM": "General Motors Company",
    "SONY": "Sony Group Corporation",
    "UBER": "Uber Technologies, Inc.",
    "ZM": "Zoom Video Communications, Inc.",
    "SQ": "Block, Inc.",
    "SHOP": "Shopify Inc.",
    "TWTR": "Twitter, Inc.",
    "SNAP": "Snap Inc.",
    "PFE": "Pfizer Inc.",
    "MRNA": "Moderna, Inc.",
    "BABA": "Alibaba Group Holding Limited",
    "BIDU": "Baidu, Inc.",
    "JD": "JD.com, Inc.",
    "NIO": "NIO Inc.",
    "LI": "Li Auto Inc.",
    "XPEV": "XPeng Inc.",
    "PDD": "PDD Holdings Inc.",
    "TCEHY": "Tencent Holdings Limited",
    "BILI": "Bilibili Inc.",
    "TAL": "TAL Education Group",
    "EDU": "New Oriental Education & Technology Group Inc.",
    "VIPS": "Vipshop Holdings Limited",
    "MOMO": "Hello Group Inc.",
    "WB": "Weibo Corporation",
    "ZTO": "ZTO Express (Cayman) Inc.",
    "HTHT": "H World Group Limited",
    "IQ": "iQIYI, Inc.",
    "LKNCY": "Luckin Coffee Inc.",
    "LVS": "Las Vegas Sands Corp.",
    "WYNN": "Wynn Resorts, Limited",
    "MGM": "MGM Resorts International",
    "CZR": "Caesars Entertainment, Inc.",
    "MAR": "Marriott International, Inc.",
    "HLT": "Hilton Worldwide Holdings Inc.",
    "BKNG": "Booking Holdings Inc.",
    "EXPE": "Expedia Group, Inc.",
    "AAL": "American Airlines Group Inc.",
    "UAL": "United Airlines Holdings, Inc.",
    "DAL": "Delta Air Lines, Inc.",
    "LUV": "Southwest Airlines Co.",
    "JBLU": "JetBlue Airways Corporation",
    "SAVE": "Spirit Airlines, Inc.",
    "RCL": "Royal Caribbean Group",
    "CCL": "Carnival Corporation & plc",
    "NCLH": "Norwegian Cruise Line Holdings Ltd."
  };
  
  export const getCompanyNameFromTicker = (ticker: string) => {
      return tickerToName[ticker] || ticker;
  };
  
  export const popularTickers = Object.keys(tickerToName); 